services:
    nginx:
        image: eleven/nginx:latest
        container_name: nginx-eleven
        build: infrastructure/nginx
        ports:
            - "${APP_NGINX_PORT:-8080}:80"
        volumes:
            - .:/var/www
        depends_on:
            - php
        networks:
            - eleven
    php:
        image: eleven/php:8.3-fpm
        container_name: php-eleven
        build: infrastructure/php
        ports:
            - "${APP_PHP_PORT:-9000}:9000"
        volumes:
            - .:/var/www
        networks:
            - eleven
    db:
        image: mysql:8.0
        container_name: db-eleven
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: eleven
            MYSQL_USER: eleven
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
        volumes:
            - ./.database/mysql:/var/lib/mysql
        depends_on:
            - php
        ports:
            - "${APP_DB_PORT:-3307}:3306"
        expose:
            - "3307"
        networks:
            - eleven
    admin:
        image: phpmyadmin:latest
        container_name: admin-eleven
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: eleven
            PMA_PASSWORD: 123456
            PMA_PMADB: eleven
        depends_on:
            - db
        ports:
            - "${APP_ADMIN_PORT:-8081}:80"
        networks:
            - eleven
networks:
    eleven:
        driver: bridge
